#!/usr/bin/env python3
"""Generate src/html_names.h: the sorted symbol table of known HTML element
names used by the external scanner for pair tags.

Run from the repo root:  python3 scripts/gen_html_names.py
"""
import pathlib

CURRENT = """
a abbr address area article aside audio b base bdi bdo blockquote body br button
canvas caption cite code col colgroup data datalist dd del details dfn dialog div dl
dt em embed fieldset figcaption figure footer form h1 h2 h3 h4 h5 h6 head header
hgroup hr html i iframe img input ins kbd label legend li link main map mark menu
meta meter nav noscript object ol optgroup option output p picture pre progress q rp
rt ruby s samp script search section select slot small source span strong style sub
summary sup table tbody td template textarea tfoot th thead time title tr track u ul
var video wbr
"""
OBSOLETE = """
acronym applet basefont bgsound big blink center dir font frame frameset isindex
keygen listing marquee menuitem multicol nextid nobr noembed noframes param plaintext
rb rtc spacer strike tt xmp
"""
FOREIGN = "svg math"

names = sorted(set((CURRENT + OBSOLETE + FOREIGN).split()))
assert all(n.isascii() and n == n.lower() for n in names)
assert len(names) < 255

cols = 6
width = max(len(n) for n in names) + 3
rows = []
for k in range(0, len(names), cols):
    chunk = names[k:k + cols]
    cells = [f'"{n}",'.ljust(width) for n in chunk]
    rows.append("    " + "".join(cells).rstrip())

out = f"""// Generated by scripts/gen_html_names.py -- do not edit by hand.
#ifndef HTML_NAMES_H_
#define HTML_NAMES_H_

// Sorted (strcmp order) so the scanner can binary-search it.
static const char *const HTML_NAMES[] = {{
{chr(10).join(rows)}
}};

#define HTML_NAMES_COUNT {len(names)}
_Static_assert(HTML_NAMES_COUNT ==
                   sizeof(HTML_NAMES) / sizeof(HTML_NAMES[0]),
               "HTML_NAMES_COUNT out of sync with HTML_NAMES");
_Static_assert(HTML_NAMES_COUNT < 255, "Too many HTML names");

#endif // HTML_NAMES_H_
"""
path = pathlib.Path(__file__).resolve().parent.parent / "src" / "html_names.h"
path.write_text(out)
print(f"wrote {path} ({len(names)} names)")
