/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 54
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_ = 1,
  aux_sym_heading_prefix_token1 = 2,
  aux_sym_heading_prefix_token2 = 3,
  aux_sym_title_token1 = 4,
  aux_sym_title_token2 = 5,
  sym__newline = 6,
  sym__line_content = 7,
  sym__section_start = 8,
  sym__section_end = 9,
  sym_document = 10,
  sym_content = 11,
  sym_subsection = 12,
  sym_heading = 13,
  sym_body = 14,
  sym_heading_prefix = 15,
  sym_title = 16,
  sym_paragraph = 17,
  aux_sym_document_repeat1 = 18,
  aux_sym_document_repeat2 = 19,
  aux_sym_document_repeat3 = 20,
  aux_sym_heading_prefix_repeat1 = 21,
  aux_sym_paragraph_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_] = "  ",
  [aux_sym_heading_prefix_token1] = "heading_prefix_token1",
  [aux_sym_heading_prefix_token2] = "heading_prefix_token2",
  [aux_sym_title_token1] = "title_token1",
  [aux_sym_title_token2] = "title_token2",
  [sym__newline] = "_newline",
  [sym__line_content] = "_line_content",
  [sym__section_start] = "_section_start",
  [sym__section_end] = "_section_end",
  [sym_document] = "document",
  [sym_content] = "content",
  [sym_subsection] = "subsection",
  [sym_heading] = "heading",
  [sym_body] = "body",
  [sym_heading_prefix] = "heading_prefix",
  [sym_title] = "title",
  [sym_paragraph] = "paragraph",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_document_repeat2] = "document_repeat2",
  [aux_sym_document_repeat3] = "document_repeat3",
  [aux_sym_heading_prefix_repeat1] = "heading_prefix_repeat1",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_] = anon_sym_,
  [aux_sym_heading_prefix_token1] = aux_sym_heading_prefix_token1,
  [aux_sym_heading_prefix_token2] = aux_sym_heading_prefix_token2,
  [aux_sym_title_token1] = aux_sym_title_token1,
  [aux_sym_title_token2] = aux_sym_title_token2,
  [sym__newline] = sym__newline,
  [sym__line_content] = sym__line_content,
  [sym__section_start] = sym__section_start,
  [sym__section_end] = sym__section_end,
  [sym_document] = sym_document,
  [sym_content] = sym_content,
  [sym_subsection] = sym_subsection,
  [sym_heading] = sym_heading,
  [sym_body] = sym_body,
  [sym_heading_prefix] = sym_heading_prefix,
  [sym_title] = sym_title,
  [sym_paragraph] = sym_paragraph,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_document_repeat2] = aux_sym_document_repeat2,
  [aux_sym_document_repeat3] = aux_sym_document_repeat3,
  [aux_sym_heading_prefix_repeat1] = aux_sym_heading_prefix_repeat1,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_heading_prefix_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading_prefix_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_title_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_title_token2] = {
    .visible = false,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__line_content] = {
    .visible = false,
    .named = true,
  },
  [sym__section_start] = {
    .visible = false,
    .named = true,
  },
  [sym__section_end] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_subsection] = {
    .visible = true,
    .named = true,
  },
  [sym_heading] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_title] = {
    .visible = true,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_document_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_document_repeat3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading_prefix_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_preamble = 1,
  field_prefix = 2,
  field_title = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_preamble] = "preamble",
  [field_prefix] = "prefix",
  [field_title] = "title",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_preamble, 0},
  [1] =
    {field_preamble, 0},
    {field_preamble, 1},
  [3] =
    {field_prefix, 1},
    {field_title, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 11,
  [18] = 12,
  [19] = 14,
  [20] = 10,
  [21] = 13,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 24,
  [32] = 23,
  [33] = 30,
  [34] = 25,
  [35] = 26,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 42,
  [46] = 40,
  [47] = 39,
  [48] = 43,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 52,
};

static const TSCharacterRange aux_sym_heading_prefix_token1_character_set_1[] = {
  {'(', ')'}, {'0', '9'}, {'<', '<'}, {'>', '>'}, {'A', '['}, {']', ']'}, {'_', '_'}, {'a', '{'},
  {'}', '}'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(aux_sym_heading_prefix_token1);
      if (eof) ADVANCE(4);
      if (lookahead == '\t') ADVANCE(11);
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(10);
      if (set_contains(aux_sym_heading_prefix_token1_character_set_1, 9, lookahead)) ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(5);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(2);
      if (('!' <= lookahead && lookahead <= '\'') ||
          ('*' <= lookahead && lookahead <= '/') ||
          lookahead == ':' ||
          lookahead == ';' ||
          lookahead == '=' ||
          lookahead == '?' ||
          lookahead == '@' ||
          lookahead == '\\') ADVANCE(9);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_heading_prefix_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      if (set_contains(aux_sym_heading_prefix_token1_character_set_1, 9, lookahead)) ADVANCE(8);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_heading_prefix_token1);
      if (set_contains(aux_sym_heading_prefix_token1_character_set_1, 9, lookahead)) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_heading_prefix_token2);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == '\t') ADVANCE(11);
      if (lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_title_token2);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 3, .external_lex_state = 2},
  [2] = {.lex_state = 3, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 1},
  [4] = {.lex_state = 0, .external_lex_state = 1},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 1},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 1},
  [10] = {.lex_state = 3, .external_lex_state = 2},
  [11] = {.lex_state = 3, .external_lex_state = 2},
  [12] = {.lex_state = 3, .external_lex_state = 2},
  [13] = {.lex_state = 3, .external_lex_state = 2},
  [14] = {.lex_state = 3, .external_lex_state = 2},
  [15] = {.lex_state = 3, .external_lex_state = 1},
  [16] = {.lex_state = 3, .external_lex_state = 1},
  [17] = {.lex_state = 3, .external_lex_state = 1},
  [18] = {.lex_state = 3, .external_lex_state = 1},
  [19] = {.lex_state = 3, .external_lex_state = 1},
  [20] = {.lex_state = 3, .external_lex_state = 1},
  [21] = {.lex_state = 3, .external_lex_state = 1},
  [22] = {.lex_state = 0, .external_lex_state = 3},
  [23] = {.lex_state = 3, .external_lex_state = 2},
  [24] = {.lex_state = 0, .external_lex_state = 4},
  [25] = {.lex_state = 0, .external_lex_state = 4},
  [26] = {.lex_state = 0, .external_lex_state = 4},
  [27] = {.lex_state = 0, .external_lex_state = 3},
  [28] = {.lex_state = 3, .external_lex_state = 1},
  [29] = {.lex_state = 0, .external_lex_state = 3},
  [30] = {.lex_state = 0, .external_lex_state = 3},
  [31] = {.lex_state = 0, .external_lex_state = 4},
  [32] = {.lex_state = 3, .external_lex_state = 1},
  [33] = {.lex_state = 0, .external_lex_state = 4},
  [34] = {.lex_state = 0, .external_lex_state = 4},
  [35] = {.lex_state = 0, .external_lex_state = 4},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 0, .external_lex_state = 3},
  [40] = {.lex_state = 0, .external_lex_state = 3},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 0, .external_lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 7},
  [45] = {.lex_state = 0, .external_lex_state = 4},
  [46] = {.lex_state = 0, .external_lex_state = 4},
  [47] = {.lex_state = 0, .external_lex_state = 4},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 12},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_] = ACTIONS(1),
    [aux_sym_heading_prefix_token1] = ACTIONS(1),
    [aux_sym_title_token1] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__line_content] = ACTIONS(1),
    [sym__section_start] = ACTIONS(1),
    [sym__section_end] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(49),
    [sym_content] = STATE(5),
    [sym_subsection] = STATE(22),
    [sym_paragraph] = STATE(11),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_document_repeat2] = STATE(5),
    [aux_sym_document_repeat3] = STATE(22),
    [aux_sym_paragraph_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym__line_content] = ACTIONS(7),
    [sym__section_start] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(7), 1,
      sym__line_content,
    ACTIONS(9), 1,
      sym__section_start,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      sym__newline,
    STATE(10), 1,
      aux_sym_document_repeat1,
    STATE(11), 1,
      sym_paragraph,
    STATE(12), 1,
      aux_sym_paragraph_repeat1,
    STATE(6), 2,
      sym_content,
      aux_sym_document_repeat2,
    STATE(29), 2,
      sym_subsection,
      aux_sym_document_repeat3,
  [30] = 8,
    ACTIONS(15), 1,
      sym__line_content,
    ACTIONS(17), 1,
      sym__section_start,
    ACTIONS(19), 1,
      sym__section_end,
    STATE(17), 1,
      sym_paragraph,
    STATE(18), 1,
      aux_sym_paragraph_repeat1,
    STATE(24), 1,
      sym_body,
    STATE(9), 2,
      sym_content,
      aux_sym_document_repeat2,
    STATE(25), 2,
      sym_subsection,
      aux_sym_document_repeat3,
  [57] = 8,
    ACTIONS(15), 1,
      sym__line_content,
    ACTIONS(17), 1,
      sym__section_start,
    ACTIONS(21), 1,
      sym__section_end,
    STATE(17), 1,
      sym_paragraph,
    STATE(18), 1,
      aux_sym_paragraph_repeat1,
    STATE(31), 1,
      sym_body,
    STATE(9), 2,
      sym_content,
      aux_sym_document_repeat2,
    STATE(34), 2,
      sym_subsection,
      aux_sym_document_repeat3,
  [84] = 7,
    ACTIONS(7), 1,
      sym__line_content,
    ACTIONS(9), 1,
      sym__section_start,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      sym_paragraph,
    STATE(12), 1,
      aux_sym_paragraph_repeat1,
    STATE(8), 2,
      sym_content,
      aux_sym_document_repeat2,
    STATE(29), 2,
      sym_subsection,
      aux_sym_document_repeat3,
  [108] = 7,
    ACTIONS(7), 1,
      sym__line_content,
    ACTIONS(9), 1,
      sym__section_start,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(11), 1,
      sym_paragraph,
    STATE(12), 1,
      aux_sym_paragraph_repeat1,
    STATE(8), 2,
      sym_content,
      aux_sym_document_repeat2,
    STATE(27), 2,
      sym_subsection,
      aux_sym_document_repeat3,
  [132] = 5,
    ACTIONS(25), 1,
      sym__line_content,
    STATE(17), 1,
      sym_paragraph,
    STATE(18), 1,
      aux_sym_paragraph_repeat1,
    ACTIONS(28), 2,
      sym__section_start,
      sym__section_end,
    STATE(7), 2,
      sym_content,
      aux_sym_document_repeat2,
  [150] = 5,
    ACTIONS(30), 1,
      sym__line_content,
    STATE(11), 1,
      sym_paragraph,
    STATE(12), 1,
      aux_sym_paragraph_repeat1,
    ACTIONS(28), 2,
      sym__section_start,
      ts_builtin_sym_end,
    STATE(8), 2,
      sym_content,
      aux_sym_document_repeat2,
  [168] = 5,
    ACTIONS(15), 1,
      sym__line_content,
    STATE(17), 1,
      sym_paragraph,
    STATE(18), 1,
      aux_sym_paragraph_repeat1,
    ACTIONS(33), 2,
      sym__section_start,
      sym__section_end,
    STATE(7), 2,
      sym_content,
      aux_sym_document_repeat2,
  [186] = 3,
    ACTIONS(37), 1,
      sym__newline,
    STATE(10), 1,
      aux_sym_document_repeat1,
    ACTIONS(35), 3,
      sym__line_content,
      sym__section_start,
      ts_builtin_sym_end,
  [198] = 3,
    ACTIONS(42), 1,
      sym__newline,
    STATE(14), 1,
      aux_sym_document_repeat1,
    ACTIONS(40), 3,
      sym__line_content,
      sym__section_start,
      ts_builtin_sym_end,
  [210] = 3,
    ACTIONS(7), 1,
      sym__line_content,
    STATE(13), 1,
      aux_sym_paragraph_repeat1,
    ACTIONS(44), 3,
      sym__section_start,
      ts_builtin_sym_end,
      sym__newline,
  [222] = 3,
    ACTIONS(48), 1,
      sym__line_content,
    STATE(13), 1,
      aux_sym_paragraph_repeat1,
    ACTIONS(46), 3,
      sym__section_start,
      ts_builtin_sym_end,
      sym__newline,
  [234] = 3,
    ACTIONS(13), 1,
      sym__newline,
    STATE(10), 1,
      aux_sym_document_repeat1,
    ACTIONS(51), 3,
      sym__line_content,
      sym__section_start,
      ts_builtin_sym_end,
  [246] = 3,
    ACTIONS(53), 1,
      sym__newline,
    STATE(16), 1,
      aux_sym_document_repeat1,
    ACTIONS(55), 3,
      sym__line_content,
      sym__section_start,
      sym__section_end,
  [258] = 3,
    ACTIONS(57), 1,
      sym__newline,
    STATE(20), 1,
      aux_sym_document_repeat1,
    ACTIONS(59), 3,
      sym__line_content,
      sym__section_start,
      sym__section_end,
  [270] = 3,
    ACTIONS(61), 1,
      sym__newline,
    STATE(19), 1,
      aux_sym_document_repeat1,
    ACTIONS(40), 3,
      sym__line_content,
      sym__section_start,
      sym__section_end,
  [282] = 3,
    ACTIONS(15), 1,
      sym__line_content,
    STATE(21), 1,
      aux_sym_paragraph_repeat1,
    ACTIONS(44), 3,
      sym__section_start,
      sym__section_end,
      sym__newline,
  [294] = 3,
    ACTIONS(57), 1,
      sym__newline,
    STATE(20), 1,
      aux_sym_document_repeat1,
    ACTIONS(51), 3,
      sym__line_content,
      sym__section_start,
      sym__section_end,
  [306] = 3,
    ACTIONS(63), 1,
      sym__newline,
    STATE(20), 1,
      aux_sym_document_repeat1,
    ACTIONS(35), 3,
      sym__line_content,
      sym__section_start,
      sym__section_end,
  [318] = 3,
    ACTIONS(66), 1,
      sym__line_content,
    STATE(21), 1,
      aux_sym_paragraph_repeat1,
    ACTIONS(46), 3,
      sym__section_start,
      sym__section_end,
      sym__newline,
  [330] = 3,
    ACTIONS(9), 1,
      sym__section_start,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    STATE(30), 2,
      sym_subsection,
      aux_sym_document_repeat3,
  [341] = 1,
    ACTIONS(46), 4,
      sym__line_content,
      sym__section_start,
      ts_builtin_sym_end,
      sym__newline,
  [348] = 3,
    ACTIONS(17), 1,
      sym__section_start,
    ACTIONS(71), 1,
      sym__section_end,
    STATE(26), 2,
      sym_subsection,
      aux_sym_document_repeat3,
  [359] = 3,
    ACTIONS(17), 1,
      sym__section_start,
    ACTIONS(71), 1,
      sym__section_end,
    STATE(33), 2,
      sym_subsection,
      aux_sym_document_repeat3,
  [370] = 3,
    ACTIONS(17), 1,
      sym__section_start,
    ACTIONS(73), 1,
      sym__section_end,
    STATE(33), 2,
      sym_subsection,
      aux_sym_document_repeat3,
  [381] = 3,
    ACTIONS(9), 1,
      sym__section_start,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    STATE(30), 2,
      sym_subsection,
      aux_sym_document_repeat3,
  [392] = 1,
    ACTIONS(77), 4,
      sym__line_content,
      sym__section_start,
      sym__section_end,
      sym__newline,
  [399] = 3,
    ACTIONS(9), 1,
      sym__section_start,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    STATE(30), 2,
      sym_subsection,
      aux_sym_document_repeat3,
  [410] = 3,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    ACTIONS(83), 1,
      sym__section_start,
    STATE(30), 2,
      sym_subsection,
      aux_sym_document_repeat3,
  [421] = 3,
    ACTIONS(17), 1,
      sym__section_start,
    ACTIONS(86), 1,
      sym__section_end,
    STATE(35), 2,
      sym_subsection,
      aux_sym_document_repeat3,
  [432] = 1,
    ACTIONS(46), 4,
      sym__line_content,
      sym__section_start,
      sym__section_end,
      sym__newline,
  [439] = 3,
    ACTIONS(81), 1,
      sym__section_end,
    ACTIONS(88), 1,
      sym__section_start,
    STATE(33), 2,
      sym_subsection,
      aux_sym_document_repeat3,
  [450] = 3,
    ACTIONS(17), 1,
      sym__section_start,
    ACTIONS(86), 1,
      sym__section_end,
    STATE(33), 2,
      sym_subsection,
      aux_sym_document_repeat3,
  [461] = 3,
    ACTIONS(17), 1,
      sym__section_start,
    ACTIONS(91), 1,
      sym__section_end,
    STATE(33), 2,
      sym_subsection,
      aux_sym_document_repeat3,
  [472] = 3,
    ACTIONS(93), 1,
      aux_sym_heading_prefix_token1,
    ACTIONS(96), 1,
      aux_sym_title_token1,
    STATE(36), 1,
      aux_sym_heading_prefix_repeat1,
  [482] = 3,
    ACTIONS(98), 1,
      aux_sym_heading_prefix_token1,
    ACTIONS(100), 1,
      aux_sym_title_token1,
    STATE(36), 1,
      aux_sym_heading_prefix_repeat1,
  [492] = 3,
    ACTIONS(102), 1,
      aux_sym_heading_prefix_token1,
    STATE(37), 1,
      aux_sym_heading_prefix_repeat1,
    STATE(44), 1,
      sym_heading_prefix,
  [502] = 1,
    ACTIONS(104), 2,
      sym__section_start,
      ts_builtin_sym_end,
  [507] = 1,
    ACTIONS(106), 2,
      sym__section_start,
      ts_builtin_sym_end,
  [512] = 2,
    ACTIONS(96), 1,
      aux_sym_title_token1,
    ACTIONS(108), 1,
      aux_sym_heading_prefix_token1,
  [519] = 1,
    ACTIONS(110), 2,
      sym__section_start,
      ts_builtin_sym_end,
  [524] = 2,
    ACTIONS(112), 1,
      anon_sym_,
    STATE(3), 1,
      sym_heading,
  [531] = 2,
    ACTIONS(114), 1,
      aux_sym_title_token1,
    STATE(15), 1,
      sym_title,
  [538] = 1,
    ACTIONS(110), 2,
      sym__section_start,
      sym__section_end,
  [543] = 1,
    ACTIONS(106), 2,
      sym__section_start,
      sym__section_end,
  [548] = 1,
    ACTIONS(104), 2,
      sym__section_start,
      sym__section_end,
  [553] = 2,
    ACTIONS(112), 1,
      anon_sym_,
    STATE(4), 1,
      sym_heading,
  [560] = 1,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
  [564] = 1,
    ACTIONS(118), 1,
      aux_sym_title_token2,
  [568] = 1,
    ACTIONS(120), 1,
      aux_sym_heading_prefix_token2,
  [572] = 1,
    ACTIONS(122), 1,
      sym__newline,
  [576] = 1,
    ACTIONS(124), 1,
      sym__newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 57,
  [SMALL_STATE(5)] = 84,
  [SMALL_STATE(6)] = 108,
  [SMALL_STATE(7)] = 132,
  [SMALL_STATE(8)] = 150,
  [SMALL_STATE(9)] = 168,
  [SMALL_STATE(10)] = 186,
  [SMALL_STATE(11)] = 198,
  [SMALL_STATE(12)] = 210,
  [SMALL_STATE(13)] = 222,
  [SMALL_STATE(14)] = 234,
  [SMALL_STATE(15)] = 246,
  [SMALL_STATE(16)] = 258,
  [SMALL_STATE(17)] = 270,
  [SMALL_STATE(18)] = 282,
  [SMALL_STATE(19)] = 294,
  [SMALL_STATE(20)] = 306,
  [SMALL_STATE(21)] = 318,
  [SMALL_STATE(22)] = 330,
  [SMALL_STATE(23)] = 341,
  [SMALL_STATE(24)] = 348,
  [SMALL_STATE(25)] = 359,
  [SMALL_STATE(26)] = 370,
  [SMALL_STATE(27)] = 381,
  [SMALL_STATE(28)] = 392,
  [SMALL_STATE(29)] = 399,
  [SMALL_STATE(30)] = 410,
  [SMALL_STATE(31)] = 421,
  [SMALL_STATE(32)] = 432,
  [SMALL_STATE(33)] = 439,
  [SMALL_STATE(34)] = 450,
  [SMALL_STATE(35)] = 461,
  [SMALL_STATE(36)] = 472,
  [SMALL_STATE(37)] = 482,
  [SMALL_STATE(38)] = 492,
  [SMALL_STATE(39)] = 502,
  [SMALL_STATE(40)] = 507,
  [SMALL_STATE(41)] = 512,
  [SMALL_STATE(42)] = 519,
  [SMALL_STATE(43)] = 524,
  [SMALL_STATE(44)] = 531,
  [SMALL_STATE(45)] = 538,
  [SMALL_STATE(46)] = 543,
  [SMALL_STATE(47)] = 548,
  [SMALL_STATE(48)] = 553,
  [SMALL_STATE(49)] = 560,
  [SMALL_STATE(50)] = 564,
  [SMALL_STATE(51)] = 568,
  [SMALL_STATE(52)] = 572,
  [SMALL_STATE(53)] = 576,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 1),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 2),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(52),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(53),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 3, 0, 3),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading, 4, 0, 3),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 3, 0, 2),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 1),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat3, 2, 0, 0),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat3, 2, 0, 0), SHIFT_REPEAT(43),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat3, 2, 0, 0), SHIFT_REPEAT(48),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_heading_prefix_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading_prefix_repeat1, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_prefix, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subsection, 4, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subsection, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_heading_prefix_repeat1, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subsection, 5, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [116] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__line_content = 0,
  ts_external_token__section_start = 1,
  ts_external_token__section_end = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__line_content] = sym__line_content,
  [ts_external_token__section_start] = sym__section_start,
  [ts_external_token__section_end] = sym__section_end,
};

static const bool ts_external_scanner_states[5][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__line_content] = true,
    [ts_external_token__section_start] = true,
    [ts_external_token__section_end] = true,
  },
  [2] = {
    [ts_external_token__line_content] = true,
    [ts_external_token__section_start] = true,
  },
  [3] = {
    [ts_external_token__section_start] = true,
  },
  [4] = {
    [ts_external_token__section_start] = true,
    [ts_external_token__section_end] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_fey_external_scanner_create(void);
void tree_sitter_fey_external_scanner_destroy(void *);
bool tree_sitter_fey_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_fey_external_scanner_serialize(void *, char *);
void tree_sitter_fey_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_fey(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_fey_external_scanner_create,
      tree_sitter_fey_external_scanner_destroy,
      tree_sitter_fey_external_scanner_scan,
      tree_sitter_fey_external_scanner_serialize,
      tree_sitter_fey_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "fey",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
